routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::group(['middleware'=>'auth'],function(){

    



Route::group(['prefix'=>'manager', 'namespace'=>'Manager'],function(){

    Route::resource('users', 'UserController');/* ->middleware('check.user-is-male'); */

    Route::resource('categories', 'CategoryController'); 
    Route::resource('products', 'ProductController'); 

    Route::resource('roles', 'RoleController');

});
// });

// Auth::routes();
Route::group(['namespace'=>'Client'], function(){

    Route::get('/homeClient', 'ClientController@index')->name('homeClient');
    // Route::resource('carts', 'CartController');

});


// Route::get('/', function () {
//     return view('manager.dashboard.index');
// });

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Category;


class Product extends Model {  
    protected $table = 'products';
    protected $primaryKey = 'id';
    protected $guarded = [];

    public function category() {
        return $this->belongsTo( Category::class, 'category_id');
    }
}

app/Http/Controllers/Manager/CategoryController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;
use App\Traits\HandleImageTrait;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $category;
    protected $product;


    public function __construct(Category $category, Product $product)
    {
        $this->category = $category;
        $this->product = $product  ;
    }


    public function index()
    {
        // $category = $this->category->first();
        // $product = $this->product->get()->take(5);

        // echo 'category:'.$category->name;

        // foreach ($products as $product => $value) {
        //     echo "Name";
        // }

        $categories=Category::all();

        return view('manager.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::all();

        return view('manager.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|max:50'
        ]);

        $category = new Category([
           'name' => $request ->get('name'),
        ]);

        $category->save();
        return redirect()->route('categories.index')->with('message', 'tạo category thành công!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('manager.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)   
    {
        $request->validate([
            'name'=>'required|max:50'
        ]);

        $category = Category::find($id);
        $category->name = $request->get('name');
        $category->save();
        return redirect()->route('categories.index')->with('message', 'sửa category thành công!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        return redirect()->route('categories.index')->with('message', 'Xóa category thành công!');
    }

}

app/Http/Controllers/Manager/ProductController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Traits\HandleImageTrait;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use App\Http\Requests\CreateProductRequest;
use DB;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $product;
    private $category;
    use HandleImageTrait;
    protected $path;

    public function __contruct( Product $product, Category $category) {
        $this->product = $product;
        $this->path = 'upload/';
        $this->category = $category;
    }

    public function index()
    {
        $products = Product::all();
        return view('manager.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        //$category = $this->category->all();
        return view('manager.product.add', compact('category'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)  
    {
        try {
            $image = $request->file('image');
            $data['name'] = $request->name;
            $data['price'] =$request->price;
            $data['image'] =$this->saveImage($image, $this->path);
            $data['category_id'] = $request->category_id;

            DB::table('products')->insert($data);
            
            return redirect()->route('products.index');


        } catch(Exception $exception) {
            DB::rollback();
            Log::error('Message: '. $exception->getMessage() . '---Line: ' . $exception->getLine());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Manager/RoleController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{

    protected $roleModel;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct(Role $roleModel)
     {
         $this->roleModel = $roleModel;
     }
 

    public function index()
    {
        $roles = $this->roleModel->where('name','!=', 'super-admin')->paginate(5);

        return view('manager.role.index')->with( 'roles',$roles);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Manager/UserController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Traits\HandleImageTrait;
use App\User;
use App\Models\Role;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    use HandleImageTrait;

    protected $path;

    protected $userModel;
    protected $roleModel;


    public function __construct(User $user, Role $role)
    {
        $this->userModel = $user;
        $this->path = 'upload/';
        $this->roleModel = $role;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->userModel->with('roles')->latest('id')->paginate(5);

        return view('manager.user.user')->with( 'users',$users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->roleModel->where('name','!=','super-admin')->get();

        return view('manager.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {

        $image = $request->file('image');
        $dataCreate = $request->all();
        $dataCreate['image'] = $this->saveImage($image, $this->path);
        $dataCreate['password'] = Hash::make($request->input('password'));

        $user = $this->userModel->create($dataCreate);

        $user->syncRoles($request->roles);

        return redirect()->route('users.index')->with('message', 'tao user thanh cong');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userModel->with('roles')->findOrFail($id);
        $roles = $this->roleModel->where('name','!=','super-admin')->get();
        $listRoleIds = $user->roles->pluck('id')->ToArray();

        return view('manager.user.edit')->with(['user'=> $user, 'roles'=>$roles,'listRoleIds'=>$listRoleIds]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
      
        $user = $this->userModel->findOrFail($id);
        $image = $request->file('image');

        $dataUpdate = $request->all();

        $dataUpdate['image'] = $this->updateImage($image, $this->path, $user->image);

        $user->update($dataUpdate);
        $user->syncRoles($request->roles);

        return redirect()->route('users.index')->with('message', 'sửa user thanh cong'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('users.index')->with('message', 'Xóa user thành công!');
    }
}

resources/views/manager/product/add.blade.php
@extends('manager.layout.app')

@section('title', 'Create Product')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create Product</div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label">{{ __('image') }}</label>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('products.store') }}"  enctype="multipart/form-data" >
                        @csrf
                        <!-- select image -->
                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <h4 class="title">Regular Image</h4>
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="../../assets/img/image_placeholder.jpg" alt="...">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                              <span class="btn btn-rose btn-round btn-file">
                                                <span class="fileinput-new">Select image</span>
                                                <span class="fileinput-exists">Change</span>
                                                <input type="file" name="image">
                                              </span>
                                        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}"  autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('price') }}</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="price" value="{{ old('price') }}"  >

                                
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Category') }}</label>

                            <div class="col-md-6">
                                <select class="selectpicker"  name="category_id" >
                                    @foreach($category as $categoryItem)
                                        <option value="<?php echo $categoryItem->id ?>">{{$categoryItem->name}}</option>
                                    @endforeach
                                </select>

                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/product/edit.blade.php
@extends('manager.layout.app')

@section('title', 'Edit Product')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Edit Product</div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label">{{ __('image') }}</label>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('products.update') }}"  enctype="multipart/form-data" >
                        @csrf
                        @method('put')
                        <!-- select image -->
                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <h4 class="title">Regular Image</h4>
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="{{asset('upload/'.$product->image)}}" alt="...">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                              <span class="btn btn-rose btn-round btn-file">
                                                <span class="fileinput-new">Select image</span>
                                                <span class="fileinput-exists">Change</span>
                                                <input type="file" name="image">
                                              </span>
                                        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}"  autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('price') }}</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="price" value="{{ old('price') }}"  >

                                
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Category') }}</label>

                            <div class="col-md-6">
                                <select class="selectpicker"  name="category_id" >
                                    @foreach($category as $categoryItem)
                                        <option value="<?php echo $categoryItem->id ?>">{{$categoryItem->name}}</option>
                                    @endforeach
                                </select>

                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/product/index.blade.php
@extends('manager.layout.app')

@section('title', 'Product')

@section('content')
<a class="btn btn-success" href="{{route('products.create')}}">Create New Product</a>
    @if(session('message'))
        <h1>{{session('message')}} </h1>
    @endif

    <table  class="table table-striped mt-3">
    <thead class="thead-dark">
        <tr>
            <td scope="col">STT</td>
            <td scope="col">Name</td>
            <td scope="col">Price</td>
            <td scope="col">Image</td>
            <td scope="col">Category</td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $productIem)
            
            <tr>
                <td scope="row">{{$productIem->id}}</td>
                <td>{{$productIem->name}}</td>
                <td>{{$productIem->price}}</td>
                
                <td>
                    <img width="100px" height="100px" src="{{asset('upload/'.$productIem->image)}}" alt="">
                </td>
                <td>{{optional($productIem->category)->name}}</td>

                <td class="table-buttons">
                    <a class="btn btn-primary" href="{{ route('products.edit', $productIem) }}"><i class="fa fa-pencil"></i></a>
                    <form METHOD="post" ACTION="{{ route('products.destroy', $productIem) }}" style="display: contents;">
                    @csrf
                    @method('DELETE')
                        <button type="submit" class="btn btn-danger">
                        <i class="fa fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    <div>
       
    </div>

@endsection