routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::group(['middleware'=>'auth'],function(){

    



Route::group(['prefix'=>'manager', 'namespace'=>'Manager'],function(){

    Route::resource('users', 'UserController');/* ->middleware('check.user-is-male'); */

    Route::resource('categories', 'CategoryController'); 
    Route::resource('products', 'ProductController'); 

    Route::resource('roles', 'RoleController');

});
// });

// Auth::routes();
Route::group(['namespace'=>'Client'], function(){

    Route::get('/homeClient', 'ClientController@index')->name('homeClient');
    // Route::resource('carts', 'CartController');

});


// Route::get('/', function () {
//     return view('manager.dashboard.index');
// });

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $primaryKey = 'id';
    protected $guarded = [];

    // public function product()
    // {
    //     return $this->hasMany('App\Models\Product','id');
    // }
    
}

app/Http/Controllers/Manager/CategoryController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;
use App\Traits\HandleImageTrait;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $category;
    protected $product;


    public function __construct(Category $category, Product $product)
    {
        $this->category = $category;
        $this->product = $product  ;
    }


    public function index()
    {
        // $category = $this->category->first();
        // $product = $this->product->get()->take(5);

        // echo 'category:'.$category->name;

        // foreach ($products as $product => $value) {
        //     echo "Name";
        // }

        $categories=Category::all();

        return view('manager.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::all();

        return view('manager.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|max:50'
        ]);

        $category = new Category([
           'name' => $request ->get('name'),
        ]);

        $category->save();
        return redirect()->route('categories.index')->with('message', 'tạo category thành công!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('manager.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)   
    {
        $request->validate([
            'name'=>'required|max:50'
        ]);

        $category = Category::find($id);
        $category->name = $request->get('name');
        $category->save();
        return redirect()->route('categories.index')->with('message', 'sửa category thành công!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        return redirect()->route('categories.index')->with('message', 'Xóa category thành công!');
    }

}

app/Http/Controllers/Manager/ProductController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Traits\HandleImageTrait;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use App\Http\Requests\CreateProductRequest;
use DB;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $product;
    private $category;
    use HandleImageTrait;
    protected $path;

    public function __contruct( Product $product, Category $category) {
        $this->product = $product;
        $this->path = 'upload/';
        $this->category = $category;
    }

    public function index()
    {
        $products = Product::all();
        return view('manager.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        //$category = $this->category->all();
        return view('manager.product.add', compact('category'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)  
    {
        try {
            $image = $request->file('image');
            $data['name'] = $request->name;
            $data['price'] =$request->price;
            $data['image'] =$this->saveImage($image, $this->path);
            $data['category_id'] = $request->category_id;

            DB::table('products')->insert($data);
            
            return redirect()->route('products.index');


        } catch(Exception $exception) {
            DB::rollback();
            Log::error('Message: '. $exception->getMessage() . '---Line: ' . $exception->getLine());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Manager/RoleController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{

    protected $roleModel;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct(Role $roleModel)
     {
         $this->roleModel = $roleModel;
     }
 

    public function index()
    {
        $roles = $this->roleModel->where('name','!=', 'super-admin')->paginate(5);

        return view('manager.role.index')->with( 'roles',$roles);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Manager/UserController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Traits\HandleImageTrait;
use App\User;
use App\Models\Role;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    use HandleImageTrait;

    protected $path;

    protected $userModel;
    protected $roleModel;


    public function __construct(User $user, Role $role)
    {
        $this->userModel = $user;
        $this->path = 'upload/';
        $this->roleModel = $role;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->userModel->with('roles')->latest('id')->paginate(5);

        return view('manager.user.user')->with( 'users',$users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->roleModel->where('name','!=','super-admin')->get();

        return view('manager.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {

        $image = $request->file('image');
        $dataCreate = $request->all();
        $dataCreate['image'] = $this->saveImage($image, $this->path);
        $dataCreate['password'] = Hash::make($request->input('password'));

        $user = $this->userModel->create($dataCreate);

        $user->syncRoles($request->roles);

        return redirect()->route('users.index')->with('message', 'tao user thanh cong');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userModel->with('roles')->findOrFail($id);
        $roles = $this->roleModel->where('name','!=','super-admin')->get();
        $listRoleIds = $user->roles->pluck('id')->ToArray();

        return view('manager.user.edit')->with(['user'=> $user, 'roles'=>$roles,'listRoleIds'=>$listRoleIds]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
      
        $user = $this->userModel->findOrFail($id);
        $image = $request->file('image');

        $dataUpdate = $request->all();

        $dataUpdate['image'] = $this->updateImage($image, $this->path, $user->image);

        $user->update($dataUpdate);
        $user->syncRoles($request->roles);

        return redirect()->route('users.index')->with('message', 'sửa user thanh cong'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('users.index')->with('message', 'Xóa user thành công!');
    }
}

resources/views/manager/category/create.blade.php
@extends('manager.layout.app')

@section('title', 'Create')

@section('content')
   <div class="row">
        <div class="col-lg-6 mx-auto">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form method="post" action="{{ route('categories.store') }}">
            @csrf
                <div class="form-group">
                    <label for="category-title">Category Name</label>
                    <input type="text" name="name" value="{{ old('name') }}" class="form-control" id="category-title">
                </div>

                <button type="submit" class="btn btn-success"> Create </button>

            </form>
        </div>
   </div>
@endsection

resources/views/manager/category/edit.blade.php
@extends('manager.layout.app')

@section('title', 'Edit'.$category->name)

@section('content')
   <div class="row">
        <div class="col-lg-6 mx-auto">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form method="post" action="{{ route('categories.update', $category) }}">
            @csrf
            @method('put')
                <div class="form-group">
                    <label for="category-title">Category Name</label>
                    <input type="text" name="name" value="{{ $category->name }}" class="form-control" id="category-title">
                </div>

                <button type="submit" class="btn btn-success"> Update </button>

            </form>
        </div>
   </div>
@endsection

resources/views/manager/category/index.blade.php
@extends('manager.layout.app')

@section('title', 'Category')

@section('content')
<a href="{{ route('categories.create') }}" class="btn btn-success">Create New Category</a>

@if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
@endif

    <table class="table table-striped mt-3">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Category ID</th>
            <th scope="col">Category Name</th>
            <th scope="col"> </th>
        </tr>
        </thead>
        <tbody>
        @foreach($categories as $category)
        <tr>
            <th scope="row">{{ $category->id }}</th>
            <td>{{ $category->name }}</td>
            <td class="table-buttons">
                <a href="{{ route('categories.edit', $category) }}" class="btn btn-primary">
                    <i class="fa fa-pencil"></i>
                </a>
                <form METHOD="post" ACTION="{{ route('categories.destroy', $category) }}" style="display: contents;">
                @csrf
                @method('DELETE')
                    <button type="submit" class="btn btn-danger">
                       <i class="fa fa-trash"></i>
                    </button>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
@endsection