routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::group(['middleware'=>'auth'],function(){

    



Route::group(['prefix'=>'manager', 'namespace'=>'Manager'],function(){

    Route::resource('users', 'UserController');/* ->middleware('check.user-is-male'); */

    Route::resource('categories', 'CategoryController'); 
    Route::resource('products', 'ProductController'); 

    Route::resource('roles', 'RoleController');

});
// });

// Auth::routes();
Route::group(['namespace'=>'Client'], function(){

    Route::get('/homeClient', 'ClientController@index')->name('homeClient');
    // Route::resource('carts', 'CartController');

});


// Route::get('/', function () {
//     return view('manager.dashboard.index');
// });

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use App\Traits\HandleImageTrait;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HandleImageTrait;
    protected $table = 'users';
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'address', 'gender', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Manager/CategoryController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;
use App\Traits\HandleImageTrait;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $category;
    protected $product;


    public function __construct(Category $category, Product $product)
    {
        $this->category = $category;
        $this->product = $product  ;
    }


    public function index()
    {
        // $category = $this->category->first();
        // $product = $this->product->get()->take(5);

        // echo 'category:'.$category->name;

        // foreach ($products as $product => $value) {
        //     echo "Name";
        // }

        $categories=Category::all();

        return view('manager.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::all();

        return view('manager.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|max:50'
        ]);

        $category = new Category([
           'name' => $request ->get('name'),
        ]);

        $category->save();
        return redirect()->route('categories.index')->with('message', 'tạo category thành công!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('manager.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)   
    {
        $request->validate([
            'name'=>'required|max:50'
        ]);

        $category = Category::find($id);
        $category->name = $request->get('name');
        $category->save();
        return redirect()->route('categories.index')->with('message', 'sửa category thành công!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        return redirect()->route('categories.index')->with('message', 'Xóa category thành công!');
    }

}

app/Http/Controllers/Manager/ProductController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Traits\HandleImageTrait;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use App\Http\Requests\CreateProductRequest;
use DB;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $product;
    private $category;
    use HandleImageTrait;
    protected $path;

    public function __contruct( Product $product, Category $category) {
        $this->product = $product;
        $this->path = 'upload/';
        $this->category = $category;
    }

    public function index()
    {
        $products = Product::all();
        return view('manager.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        //$category = $this->category->all();
        return view('manager.product.add', compact('category'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)  
    {
        try {
            $image = $request->file('image');
            $data['name'] = $request->name;
            $data['price'] =$request->price;
            $data['image'] =$this->saveImage($image, $this->path);
            $data['category_id'] = $request->category_id;

            DB::table('products')->insert($data);
            
            return redirect()->route('products.index');


        } catch(Exception $exception) {
            DB::rollback();
            Log::error('Message: '. $exception->getMessage() . '---Line: ' . $exception->getLine());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Manager/RoleController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{

    protected $roleModel;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct(Role $roleModel)
     {
         $this->roleModel = $roleModel;
     }
 

    public function index()
    {
        $roles = $this->roleModel->where('name','!=', 'super-admin')->paginate(5);

        return view('manager.role.index')->with( 'roles',$roles);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Manager/UserController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Traits\HandleImageTrait;
use App\User;
use App\Models\Role;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    use HandleImageTrait;

    protected $path;

    protected $userModel;
    protected $roleModel;


    public function __construct(User $user, Role $role)
    {
        $this->userModel = $user;
        $this->path = 'upload/';
        $this->roleModel = $role;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->userModel->with('roles')->latest('id')->paginate(5);

        return view('manager.user.user')->with( 'users',$users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->roleModel->where('name','!=','super-admin')->get();

        return view('manager.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {

        $image = $request->file('image');
        $dataCreate = $request->all();
        $dataCreate['image'] = $this->saveImage($image, $this->path);
        $dataCreate['password'] = Hash::make($request->input('password'));

        $user = $this->userModel->create($dataCreate);

        $user->syncRoles($request->roles);

        return redirect()->route('users.index')->with('message', 'tao user thanh cong');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userModel->with('roles')->findOrFail($id);
        $roles = $this->roleModel->where('name','!=','super-admin')->get();
        $listRoleIds = $user->roles->pluck('id')->ToArray();

        return view('manager.user.edit')->with(['user'=> $user, 'roles'=>$roles,'listRoleIds'=>$listRoleIds]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
      
        $user = $this->userModel->findOrFail($id);
        $image = $request->file('image');

        $dataUpdate = $request->all();

        $dataUpdate['image'] = $this->updateImage($image, $this->path, $user->image);

        $user->update($dataUpdate);
        $user->syncRoles($request->roles);

        return redirect()->route('users.index')->with('message', 'sửa user thanh cong'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('users.index')->with('message', 'Xóa user thành công!');
    }
}

resources/views/manager/user/create.blade.php
@extends('manager.layout.app')

@section('title', 'Creare Users')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create User</div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label">{{ __('image') }}</label>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('users.store') }}"  enctype="multipart/form-data" >
                        @csrf

                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <h4 class="title">Regular Image</h4>
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="../../assets/img/image_placeholder.jpg" alt="...">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                              <span class="btn btn-rose btn-round btn-file">
                                                <span class="fileinput-new">Select image</span>
                                                <span class="fileinput-exists">Change</span>
                                                <input type="file" name="image">
                                              </span>
                                        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}"  autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label ">address</label>
                            <div class="col-md-6">
                                <textarea id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address"  autocomplete="address" autofocus >
                                    {{ old('address') }}
                                </textarea>
                                @error('address')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('phone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}"  autocomplete="phone" autofocus>

                                @error('phone')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Roles') }}</label>

                            <div class="col-md-6">
                                <select class="selectpicker" data-live-search="true" name="roles[]" multiple data-style="select-with-transition">
                                    @foreach($roles as $item)
                                        <option value="{{$item->id}}">{{$item->display_name}}</option>
                                    @endforeach
                                </select>

                                @error('phone')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>



                        <div class="form-group row">
                            <label for="name" class="col-md-0 col-form-label ">{{ __('Gender') }}</label>

                            <div class="col-md-6 ">

                                <select name="gender" class="form-control bootstrap-select ">
                                    <option value="1">Male</option>
                                    <option value="0">FeMale</option>
                                </select>
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}"  autocomplete="email">

                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label ">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password"  autocomplete="new-password">

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label ">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation"  autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/user/edit.blade.php
@extends('manager.layout.app')

@section('title', 'Edit Users')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Edit User</div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label">{{ __('image') }}</label>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('users.update', $user->id) }}"  enctype="multipart/form-data" >
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <h4 class="title">Regular Image</h4>
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="{{asset('upload/'.$user->image)}}" alt="...">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                              <span class="btn btn-rose btn-round btn-file">
                                                <span class="fileinput-new">Select image</span>
                                                <span class="fileinput-exists">Change</span>
                                                <input type="file" name="image">
                                              </span>
                                        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}"  autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label ">address</label>
                            <div class="col-md-6">
                                <textarea id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address"  autocomplete="address" autofocus >
                                    {{ $user->address }}
                                </textarea>
                                @error('address')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Roles') }}</label>

                            <div class="col-md-6">
                                <select class="selectpicker" data-live-search="true" name="roles[]" multiple data-style="select-with-transition">
                                    @foreach($roles as $item)
                                        <option value="{{$item->id}}"  {{in_array($item->id, $listRoleIds) ? 'selected' : '' }}  >{{$item->display_name}}</option>
                                    @endforeach
                                </select>

                                @error('phone')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('phone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{$user->phone }}"  autocomplete="phone" autofocus>

                                @error('phone')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group col-6">
                            <label for="exampleFormControlSelect1">{{ __('Gender') }}</label>
                            <select class="form-control selectpicker" data-style="btn btn-link" value="{{$user->gender}}" id="gender" name ="gender">
                                <option value="1">Male</option>
                                <option value="0">FeMale</option>
                            </select>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}"  autocomplete="email">

                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Edit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/user/user.blade.php
@extends('manager.layout.app')

@section('title', 'Users')

@section('content')
<a class="btn btn-success" href="{{route('users.create')}}">Create New User</a>
    @if(session('message'))
        <h1>{{session('message')}} </h1>
    @endif
    

    <table  class="table table-striped mt-3">
        <thead class="thead-dark">
            <tr>
                <td scope="col">UserID</td>
                <td scope="col">Name</td>
                <td scope="col">Role</td>
                <td scope="col">Image</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td scope="row">{{$loop->iteration}}</td>
                <td>{{$user->name}}</td>
                <td>
                    @if($user->roles->count() >0)
                        @foreach($user->roles as $role)
                            {{$role->display_name .','}}
                        @endforeach
                    @endif
                </td>
                <td>
                    <img width="100px" height="100px" src="{{asset('upload/'.$user->image)}}" alt="">
                </td>
                <td class="table-buttons" style="text-align: right;">
                    <!-- <a class="btn btn-warning text-white" href="{{route('users.edit', $user->id)}}">Edit</a>
                    <button class="btn btn-danger">DELETE</button> -->
                    <a href="{{ route('users.edit', $user) }}" class="btn btn-primary">
                    <i class="fa fa-pencil"></i>
                    </a>
                    <form METHOD="post" ACTION="{{ route('users.destroy', $user) }}" style="display: contents;">
                    @csrf
                    @method('DELETE')
                        <button type="submit" class="btn btn-danger">
                        <i class="fa fa-trash"></i>
                        </button>
                    </form>

                </td>
            </tr>
        @endforeach
    </table>


    <div>
        {{ $users->links() }}
    </div>

@endsection